apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    app: backend                       # Matches the Pods with this label
  ports:
  - protocol: TCP
    port: 5000                         # Service port
    targetPort: 5000                   # Pod container port
  type: ClusterIP                      # Default service type for internal communication