apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  ports:
  - port: 5432                        # PostgreSQL default port
    targetPort: 5432
  selector:
    app: postgres                     # Matches the Pods in the StatefulSet
  type: ClusterIP                     # Default Service type for internal communication
