apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80                # Port exposed by the Service
    targetPort: 80          # Port exposed by the container
    nodePort: 8080         # NodePort to access the app externally
  type: NodePort
